catalog/urls.py
from django.conf.urls import url
from catalog import views as cat


urlpatterns = [
    url(r'^$', cat.product_list, name='product_list'),
    url(r'^(?P<slug>[\w_-]+)/$', cat.category, name='category'),
    url(r'^produtos/(?P<slug>[\w_-]+)/$', cat.product, name='product'),
]

checkout/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^carrinho/adicionar/(?P<slug>[\w_-]+)/$',
        views.create_cartitem,
        name='create_cartitem'
    ),
    url(r'^carrinho/$', views.cart_item, name='cart_item'),
    url(r'^finalizando/$', views.checkout, name='checkout'),
    url(r'^meus-pedidos/$', views.order_list, name='order_list'),
    url(r'^meus-pedidos/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
]

core/urls.py
from django.conf.urls import url
from core import views as c

djangoecommerce/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from core import views as c

urlpatterns = [
    url(r'^$', c.index, name='index'),
    url(r'^contato/$', c.contact, name='contact'),
    url(
        r'^entrar/$',
        login,
        {'template_name': 'login.html'},
        name='login'
    ),
    url(r'^sair/$', logout, {'next_page': 'index'}, name='logout'),
    # url(r'^registro/$', c.register, name='register'),
    url(r'^catalogo/', include('catalog.urls', namespace='catalog')),
    url(r'^conta/', include('accounts.urls', namespace='accounts')),
    url(r'^compras/', include('checkout.urls', namespace='checkout')),
    url(r'^admin/', admin.site.urls),
]

catalog/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Category(models.Model):
    name = models.CharField('nome', max_length=100)
    slug = models.SlugField('identificador', max_length=100)
    created = models.DateTimeField('criado em', auto_now_add=True)
    modified = models.DateTimeField('modificado em', auto_now=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:category', kwargs={'slug': self.slug})


class Product(models.Model):
    name = models.CharField('nome', max_length=100)
    slug = models.SlugField('identificador', max_length=100)
    category = models.ForeignKey('catalog.Category', verbose_name='categoria')
    description = models.TextField('descrição', blank=True)
    price = models.DecimalField('preço', decimal_places=2, max_digits=5)
    created = models.DateTimeField('criado em', auto_now_add=True)
    modified = models.DateTimeField('modificado em', auto_now=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'produto'
        verbose_name_plural = 'produtos'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'slug': self.slug})

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Category, Product


# def product_list(request):
#     products = Product.objects.all()
#     context = {'product_list': products}
#     return render(request, 'catalog/product_list.html', context)


class ProductListView(generic.ListView):
    model = Product
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'
    paginate_by = 3

product_list = ProductListView.as_view()


# def category(request, slug):
#     category = Category.objects.get(slug=slug)
#     products = Product.objects.filter(category=category)
#     context = {
#         'current_category': category,
#         'product_list': products,
#     }
#     return render(request, 'catalog/category.html', context)


class CategoryListView(generic.ListView):
    model = Category
    template_name = 'catalog/category.html'
    context_object_name = 'product_list'
    paginate_by = 3

    def get_queryset(self):
        # category = get_object_or_404(Category, slug=self.kwargs['slug'])
        # return Product.objects.filter(category=category) OU
        return Product.objects.filter(category__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['current_category'] = get_object_or_404(
            Category, slug=self.kwargs['slug'])
        return context

category = CategoryListView.as_view()


def product(request, slug):
    product = Product.objects.get(slug=slug)
    context = {
        'product': product,
    }
    return render(request, 'catalog/product.html', context)

catalog/templates/catalog/_product.html
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">
    <a href="{{ product.get_absolute_url }}">
      <img src="http://placehold.it/350x250" alt="" />
    </a>
    <div class="caption">
      <h3>{{ product}}</h3>
      {{ product.description|linebreaks }}
      <p><a href="{{ product.get_absolute_url }}" class="btn btn-success" role="button">Detalhes</a> <a href="{% url 'checkout:create_cartitem' product.slug %}" class="btn btn-default" role="button">Adicionar</a></p>
    </div>
  </div>
</div>

catalog/templates/catalog/category.html
{% extends "base.html" %}
{% load pagination %}

{% block title %}
  {{ current_category }} | {{ block.super }}
{% endblock title %}

{% block container %}
  <div class="page-header">
    <h1>{{ current_category }}</h1>
  </div>
  <div class="row">
    {% for product in product_list %}
      {% include "catalog/_product.html" %}
    {% endfor %}
  </div>
  {% pagination request paginator page_obj %}
{% endblock container %}

catalog/templates/catalog/product.html
{% extends "base.html" %}
{% block title %}
  {{ product }} | {{ block.super }}
{% endblock title %}
{% block container %}
  <div class="page-header">
    <h1>{{ product }}</h1>
  </div>
  <div class="row">
    <div class="col-sm-4">
      <a href="#" class="thumbnail">
        <img src="http://placehold.it/350x250" alt="" />
      </a>
    </div>
    <div class="col-sm-8">
      <p class="text-right">
        <a href="{% url 'checkout:create_cartitem' product.slug %}">Adicionar ao Carrinho</a>
      </p>
      {{ product.description|linebreaks }}
    </div>
  </div>
{% endblock container %}

catalog/templates/catalog/product_list.html
{% extends "base.html" %}
{% load pagination %}

{% block title %}
  Lista de Produtos | {{ block.super }}
{% endblock title %}

{% block container %}
  <div class="page-header">
    <h1>Produtos</h1>
  </div>
  <div class="row">
    {% for product in products %}
      {% include "catalog/_product.html" %}
    {% endfor %}
  </div>
  {% pagination request paginator page_obj %}
{% endblock container %}